import { executeShopifyGraphQL, getShopifyToken } from '../services/shopify/productSync';

async function createDefinitions() {
  const shop = 'onlycardz.myshopify.com';
  const token = await getShopifyToken(shop);
  
  if (!token) {
    console.error('No token found for store!');
    process.exit(1);
  }

  const definitions = [
    { name: 'PIM Product Title', key: 'product_title', type: 'single_line_text_field' },
    { name: 'PIM Price', key: 'price', type: 'single_line_text_field' },
    { name: 'PIM Weight', key: 'weight', type: 'single_line_text_field' },
    { name: 'PIM Tags', key: 'tags', type: 'single_line_text_field' }
  ];

  const mutation = `
    mutation CreateMetafieldDefinition($definition: MetafieldDefinitionInput!) {
      metafieldDefinitionCreate(definition: $definition) {
        createdDefinition {
          id
          name
        }
        userErrors {
          field
          message
        }
      }
    }
  `;

  console.log('🚀 Bootstrapping Core Metafield Definitions on Shopify...');

  for (const def of definitions) {
    const dInput = {
      name: def.name,
      namespace: 'pg__pim',
      key: def.key,
      description: 'System definition securely generated by Pendulum Ops Middleware.',
      type: def.type,
      ownerType: 'PRODUCT',
      pin: true
    };

    try {
      const result = await executeShopifyGraphQL(shop, token, mutation, { definition: dInput }, 'system-init');
      
      if (result.metafieldDefinitionCreate?.userErrors?.length > 0) {
        // Many errors will just be "Namespace and key are already in use" which is completely fine natively!
        const msg = result.metafieldDefinitionCreate.userErrors.map((e: any) => e.message).join(', ');
        if (msg.includes('Namespace and key have already been taken') || msg.includes('has already been taken')) {
           console.log(`✅ [SKIPPED] ${def.name} definition already securely exists natively.`);
        } else {
           console.error(`💥 [ERROR] Failed to map ${def.name}:`, msg);
        }
      } else {
        console.log(`✨ [CREATED] Successfully built store schema definition organically for: ${def.name}`);
      }
    } catch (err: any) {
      console.error(`💥 [NETWORK ERROR] Fault mapping definition ${def.name}:`, err.message);
    }
  }

  console.log('🏁 Execution safely finalized.');
  process.exit(0);
}

createDefinitions();
